### PR TITLE
(pdk#283) Add example .fixtures.yml

### PR DESCRIPTION
**Pull request by DavidS**
This example files makes fixtures download more discoverable, and points
folks towards the documentation.

Closes https://github.com/puppetlabs/pdk/issues/283

### CODE REVIEW

**Comment by DavidS** [comment]
Idea via https://github.com/puppetlabs/pdk/issues/283

**Comment by darkn3rd** [comment]
How would I used this?  I generated a class, and no fixtures were generated. :'(

**Comment by DavidS** [comment]
@darkn3rd There is some documentation for the fixtures.yml in https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures

**Comment by DavidS** [comment]
@darkn3rd Please also note that this repo is in hibernation and only here to support early pdk versions. Current development happens in https://github.com/puppetlabs/pdk-templates

**Pull request merged**
